[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Enable Git LFS
[build.processing]
  skip_processing = false

[[plugins]]
  package = "netlify-plugin-git-lfs"
